### ISSUE TITLE
Attest button gives Server Error (500)

### ISSUE THREAD

**Issue by Lulcaz** [datasektionen/GOrdian#1]
Only happens on expenses. Invoices send you to the attest page as expected.

**Comment by Herkarl** [comment]
Is this an issue for datasektionen/cashflow? Or is GOrdian giving a 500 response to something (exactly which request on that case?), causing cashflow to fail?

**Comment by Lulcaz** [comment]
Likely an issue with cashflow. It seems to work now.

**Comment by foodelevator** [comment]
Maybe it was this fix? <https://github.com/datasektionen/cashflow/commit/22d7872e3a316d88cbaa380ddc041793499c6e5c>
